# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    only_user:
        label: waka.utils::lang.job_list.scopes.only_user
        type: checkbox
        default: 1
        scope: onlyUser

    not_end:
        label:  waka.utils::lang.job_list.scopes.not_end
        type: checkbox
        conditions: state <> 'Terminé'


    #     label: Afficher les exemples
    #     type: switch
    #     default: 1
    #     conditions:
    #         - is_ex <> true
    #         - is_ex = true
    